language: python
python:
- 3.6
- 2.7
install:
- pip install -e .
- pip install .[test]
script:
- py.test -s tests/unit --color=yes -v
- flake8 cumulus tests
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: brettswift
  password:
    secure: iuYkhYDUHxrZqNq7XDWP+IGBqUTl3pkMhgU1NhuoEHoVgFf7F8Nlzim7qWAEpPQhEwvCqqFoo+OyrtkSx/ktKhzJeyoOhUJRwFsUUtMIoUzIPnwq51d06SSbiGOZfWmNf9mtHtSGrDxiHALS075Ru8wMJsuc7a+TK56geRnRfX+UxDPid2RAV3uPoHjxGsW5K8Ot6Tqh1/OyfUhLf2pMGbdja+CfpwLpp6qpuxGP7PaYQvMx0AVBmaKDdydJzZoieehTMPO13swN0okI1lgcaPd5gB8CGaDHtgFSp0Gmdgs/BXQl60TVozknvyz/jsV+wgUiY0brDBI6vQow3N90kzkBl/dljYO4QpNqJd6LT4ow+1mY/yYYgub0Ct4SbT+0OuUvWPfPLTljan6KTMGqqU9woMed00BsfzhHLr7vdL3qebgIP9fOOAPRE9WHWXIPk7FXOGludqh0LFCM7ANx7tKtjLl1wJDOcEwkKMfJ2CuiajsJFimWQ/eckP8ujAQV6SSTTBc+uEwhhiT0D0XDi1+ocKTDurpK6SD8Wde9Uqe47cGpj2OFY0Bb2Kw35kCXR/beJCgSYz/uMbDCvjiZah6g1fmnd8p2NbKZjfM8qKKuFw+jdhKe6LgkqNhGXujXXEjkiwJNEfjz18XCC64m9YzO5bOLhtYWNVhVCD1sKrg=
  on:
    tags: true
    repo: brettswift/cumulus
    python: 3.6
    branch: master
