language: python
python:
- 3.6
- 2.7
install:
- pip install -e .
- pip install .[test]
script:
- py.test -s tests/unit --color=yes -v
- flake8 cumulus tests
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: brettswift
  password:
    secure: UZ4n5lrB/Zhc9335zKOJPYM3XdfbScCiQALtZl2f5CnefEUkmWDY4RY9oL5OCtMTZVhVwuGkJgnBRUjRivZ5hoXCXlmOMZ3yrTd9khgFrhoBNfoiKkVEYxe14Kk2oaxtJe5Lju4xx62dTltxm410lbaZIX/tIHuW4U/SMOs6eogYwaPGaGCq1vuo/u3OJRRPmkS6PJlni++QMzTMERpWSPzXiWVmb2smTn5WECp5fc5oRPHViCS04hql9z+KOvBxMnFwO7ffalsYDG0sAO4HlCRlUxes5MMGDraLwj7DVc7jMnhjn5dVvMtfK76egbaXBGpbMs0FSfnhfWFe0EY34f1QHadBKFi2h+3BktyBGk8oI2UcQUhFkAaBv3kRKtOXpRorot32v+YqLT+3PMkfG+3pGy5uWZUUAxTfxIpKellvebj1Vcg3u4+6WDKix4goaSFCn9ifFThJj3fy7R9jubYiQ+qKxEbTwx7OAncRe6e6Q8VFe7pWUFDON5LYhfMZPSQLXelHTTtHBSC59fkrcZsNaE+Orfw4jZ1m//j6SMAkUiR1xo1Zfav0Mn67R3Ns1pmnwdzm6C7pCJTxeT1HKXLzaWgAIJCReto4JV6Cm+oxePd1/s14arMglzjmqZYvFVi7TOwbShObq/0DJoU4v2OeocXDuw7uXPv+3WYGou8=
  on:
    tags: true
    repo: brettswift/cumulus
    python: 3.6
    branch: master
