language: python
python:
- 3.6
- 2.7
install:
- pip install -e .
- pip install .[test]
script:
- py.test -s tests/unit --color=yes -v
- flake8 cumulus tests
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: brettswift
  password: $PYPI_PASSWORD
  on:
    tags: true
    repo: brettswift/cumulus
    python: 3.6
    branch: master
